"""priority check, created_at and unfinished deadline indexes

Revision ID: 96bd938b6cbe
Revises: df0fcc71051d
Create Date: 2026-09-28 14:04:25.309213

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96bd938b6cbe"
down_revision: str | Sequence[str] | None = "df0fcc71051d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # CHECK constraints are not detected by autogenerate: added manually.
    op.create_check_constraint(op.f("ck_tasks_priority_range"), "tasks", "priority BETWEEN 1 AND 3")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_tasks_created_at", "tasks", ["created_at"], unique=False)
    op.create_index(
        "ix_tasks_unfinished_deadline",
        "tasks",
        ["deadline"],
        unique=False,
        postgresql_where=sa.text("(status NOT IN ('cancelled', 'done'))"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_tasks_unfinished_deadline",
        table_name="tasks",
        postgresql_where=sa.text("(status NOT IN ('cancelled', 'done'))"),
    )
    op.drop_index("ix_tasks_created_at", table_name="tasks")
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_tasks_priority_range"), "tasks", type_="check")
